import logging
from typing import Optional, Dict, List
import discord
from google import genai
from google.genai import types

import config
import tools

logger = logging.getLogger("ai_service")

# Initialize Gemini Client if API key is provided
client: Optional[genai.Client] = None
if config.GEMINI_API_KEY:
    client = genai.Client(api_key=config.GEMINI_API_KEY)

MODEL_NAME = "gemini-2.5-flash"

SYSTEM_INSTRUCTION = (
    "You are a witty, grounded, chill friend who talks naturally in Discord servers. "
    "Keep your tone casual, friendly, and conversational, like a real Discord community member. "
    "When interacting with authorized moderators, you have access to server moderation tools "
    "which you can execute on their behalf. Always respond naturally after executing any requested moderation tools."
)

MODERATION_TOOLS = [
    tools.create_voice_channel,
    tools.set_channel_read_only,
    tools.timeout_user,
    tools.purge_messages,
]

TOOL_MAP = {
    "create_voice_channel": tools.create_voice_channel,
    "set_channel_read_only": tools.set_channel_read_only,
    "timeout_user": tools.timeout_user,
    "purge_messages": tools.purge_messages,
}

# Per-channel history storage
CHANNEL_HISTORIES: Dict[int, List[types.Content]] = {}
MAX_HISTORY_ITEMS = 20


def get_client() -> genai.Client:
    """Helper to retrieve or initialize Gemini Client."""
    global client
    if client is None:
        if not config.GEMINI_API_KEY:
            raise ValueError("GEMINI_API_KEY is not set in environment variables.")
        client = genai.Client(api_key=config.GEMINI_API_KEY)
    return client


def clear_channel_history(channel_id: int):
    """Clear history for a given channel."""
    if channel_id in CHANNEL_HISTORIES:
        del CHANNEL_HISTORIES[channel_id]


async def process_chat_message(
    guild: Optional[discord.Guild],
    channel_id: int,
    author_name: str,
    message_content: str,
    is_authorized: bool,
) -> str:
    """
    Process an incoming message through Gemini AI model.

    Args:
        guild: The Discord Guild context (if in a server channel).
        channel_id: ID of the Discord channel.
        author_name: Name of the message author.
        message_content: Content of the message.
        is_authorized: Whether the author is authorized to use moderation tools.

    Returns:
        The response text generated by Gemini.
    """
    ai_client = get_client()

    # Set active guild context for tool executions in this context
    guild_token = tools.current_guild.set(guild)

    try:
        if channel_id not in CHANNEL_HISTORIES:
            CHANNEL_HISTORIES[channel_id] = []

        history = CHANNEL_HISTORIES[channel_id]

        formatted_user_msg = f"{author_name}: {message_content}"
        user_content = types.Content(
            role="user",
            parts=[types.Part.from_text(text=formatted_user_msg)]
        )
        history.append(user_content)

        # Configure tools only if user is authorized
        tool_config = MODERATION_TOOLS if is_authorized else None

        gen_config = types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            tools=tool_config,
        )

        max_turns = 5
        turn_count = 0

        while turn_count < max_turns:
            turn_count += 1

            response = ai_client.models.generate_content(
                model=MODEL_NAME,
                contents=history,
                config=gen_config,
            )

            # Append model response content to history if available
            if response.candidates and response.candidates[0].content:
                history.append(response.candidates[0].content)

            # Check for function calls
            if response.function_calls:
                tool_response_parts = []
                for function_call in response.function_calls:
                    func_name = function_call.name
                    func_args = function_call.args or {}

                    logger.info(f"Executing tool '{func_name}' with args {func_args}")

                    if func_name in TOOL_MAP:
                        tool_func = TOOL_MAP[func_name]
                        try:
                            # Execute the moderation tool function
                            result_str = await tool_func(**func_args)
                        except Exception as e:
                            result_str = f"Error executing {func_name}: {str(e)}"
                    else:
                        result_str = f"Error: Unknown tool '{func_name}'."

                    tool_response_parts.append(
                        types.Part.from_function_response(
                            name=func_name,
                            response={"result": result_str}
                        )
                    )

                # Append function execution response as user role
                tool_content = types.Content(
                    role="user",
                    parts=tool_response_parts
                )
                history.append(tool_content)
            else:
                # Maintain sliding window history
                if len(history) > MAX_HISTORY_ITEMS:
                    CHANNEL_HISTORIES[channel_id] = history[-MAX_HISTORY_ITEMS:]

                return response.text or "I'm not sure how to respond to that!"

        # Trim history
        if len(history) > MAX_HISTORY_ITEMS:
            CHANNEL_HISTORIES[channel_id] = history[-MAX_HISTORY_ITEMS:]

        return "Completed task execution."
    finally:
        tools.current_guild.reset(guild_token)
